### ISSUE TITLE
function __()

### ISSUE THREAD

**Issue by jonyhayama** [delight-im/PHP-I18N#1]
Hi, I stumbled upon you class localization while cheking ideas to create my own and I loved your idea to create a function that merges gettext and sprintf! I just think it could be better written... here's what you have:

``` php
function __($str, $r1, $r2 = NULL, $r3 = NULL, $r4 = NULL, $r5 = NULL, $r6 = NULL, $r7 = NULL, $r8 = NULL) {
    return sprintf(_($str), $r1, $r2, $r3, $r4, $r5, $r6, $r7, $r8);
}
```

I believe it should be something like

``` php
function __( $str ){
    $args = func_get_args();
    $args[0] = _( $str );
    return call_user_func_array( 'sprintf', $args );
}
```

This way we translate the first parameter ($str) and pass everything to sprintf. I mean, if you need a sprintf with 9 params, you function will ignore the last param...

**Comment by ocram** [comment]
Thank you very much!

This syntax had been considered as well. But the ugly way with those hard-coded parameters had two advantages:
- It was obviously faster because there was _no_ overhead in any place and no additional function calls
- It would cause most IDEs to show warnings for a missing second parameter.

But actually measuring the performance has now shown that we're talking about roughly `0.0047ms` vs `0.0076ms` per operation -- which is incredible micro-optimization without any real-world benefits.

So the implementation has now been changed: https://github.com/delight-im/PHP-I18N/commit/10bcf1555bb731479dd2bccf34afb7bf8af44d23

Thank you!

Still any reason why you'd need to roll your own solution? :)

**Comment by jonyhayama** [comment]
I understand and you're very welcome ^^

I don't really have any particular need to roll my own solution, yours seems to work just fine!

The only extra thing I've done, actually, is to add an extra function:

``` php
function _e($str){
    echo call_user_func_array( '__', func_get_args() );
}
```

it's just a shortcut to echo stuff in situations like

``` php
<strong><?php _e('My String') ?></strong>
```

I know most people turn their noses up at php in the middle of html, but I kind of prefer it over all those template solutions....just my humble opinion... :)

**Comment by ocram** [comment]
That's fine!

We won't add the `_e(...)` function here for consistency with `_` (the single underscore) which doesn't have such a function, either.

But extending the functionality by adding your own functions (usually in a separate file) is perfectly okay, of course :)
