### ISSUE TITLE
Undefined constant LC_MESSAGES

### ISSUE THREAD

**Issue by zukilover** [delight-im/PHP-I18N#2]
I got this strange error and couldn't figure out what's the problem. What might cause such issue?

```
Notice: Use of undefined constant LC_MESSAGES - assumed 'LC_MESSAGES' in
..\I18N.php on line 54
```

**Comment by redelschaap** [comment]
I got it too once, it turned out my system didn't define the `LC_MESSAGES` constant. So I defined it myself:

```
if ( ! defined( 'LC_MESSAGES' ) ) {
    define( 'LC_MESSAGES', 5 );
}
```

**Comment by ocram** [comment]
Thanks a lot for your help, @redelschaap!

@zukilover: You may try the solution provided by @redelschaap, which should work because it's correctly defining the unknown constant.

If you wonder why the constant is missing, the [PHP manual says](http://php.net/manual/en/function.setlocale.php) that it's only "available if PHP was compiled with libintl".
